### Word Embedding Techniques using Embedding layers in keras

In [1]:
### Libaries used TENSORFLOW 2.0 AND KERAS


In [3]:
## tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
## vocabulary size
voc_size=10000

### One Hot Representation

In [9]:
onehot_rep = [one_hot(words,voc_size)for words in sent]
onehot_rep

[[94, 3902, 1246, 1458],
 [94, 3902, 1246, 4381],
 [94, 9721, 1246, 1468],
 [7585, 123, 1185, 9163, 3779],
 [7585, 123, 1185, 9163, 8433],
 [5264, 94, 3159, 1246, 3582],
 [9174, 1862, 9379, 9163]]

## Word Embedding Presentation

In [12]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [13]:
import numpy as np

In [18]:
sent_length = 8
embedded_docs = pad_sequences(onehot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0   94 3902 1246 1458]
 [   0    0    0    0   94 3902 1246 4381]
 [   0    0    0    0   94 9721 1246 1468]
 [   0    0    0 7585  123 1185 9163 3779]
 [   0    0    0 7585  123 1185 9163 8433]
 [   0    0    0 5264   94 3159 1246 3582]
 [   0    0    0    0 9174 1862 9379 9163]]


In [20]:
dim=10

In [21]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [22]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [23]:
model.predict(embedded_docs)

array([[[-0.02345471, -0.04141667, -0.01409798, -0.00910827,
         -0.01222485,  0.04192827,  0.03577692, -0.00618521,
         -0.01289295, -0.00739782],
        [-0.02345471, -0.04141667, -0.01409798, -0.00910827,
         -0.01222485,  0.04192827,  0.03577692, -0.00618521,
         -0.01289295, -0.00739782],
        [-0.02345471, -0.04141667, -0.01409798, -0.00910827,
         -0.01222485,  0.04192827,  0.03577692, -0.00618521,
         -0.01289295, -0.00739782],
        [-0.02345471, -0.04141667, -0.01409798, -0.00910827,
         -0.01222485,  0.04192827,  0.03577692, -0.00618521,
         -0.01289295, -0.00739782],
        [-0.01450453, -0.01440642,  0.03293731,  0.00886257,
          0.03727194, -0.0357874 , -0.01799693, -0.04925479,
         -0.04263745,  0.00795504],
        [ 0.04482749, -0.03789061,  0.00163288, -0.02791963,
          0.04920706, -0.01077952,  0.01373303, -0.0020059 ,
          0.00710426,  0.01096855],
        [-0.03359409, -0.03590824, -0.04219388, -0.0

In [24]:
embedded_docs[0]

array([   0,    0,    0,    0,   94, 3902, 1246, 1458])

In [25]:
print(model.predict(embedded_docs)[0])

[[-0.02345471 -0.04141667 -0.01409798 -0.00910827 -0.01222485  0.04192827
   0.03577692 -0.00618521 -0.01289295 -0.00739782]
 [-0.02345471 -0.04141667 -0.01409798 -0.00910827 -0.01222485  0.04192827
   0.03577692 -0.00618521 -0.01289295 -0.00739782]
 [-0.02345471 -0.04141667 -0.01409798 -0.00910827 -0.01222485  0.04192827
   0.03577692 -0.00618521 -0.01289295 -0.00739782]
 [-0.02345471 -0.04141667 -0.01409798 -0.00910827 -0.01222485  0.04192827
   0.03577692 -0.00618521 -0.01289295 -0.00739782]
 [-0.01450453 -0.01440642  0.03293731  0.00886257  0.03727194 -0.0357874
  -0.01799693 -0.04925479 -0.04263745  0.00795504]
 [ 0.04482749 -0.03789061  0.00163288 -0.02791963  0.04920706 -0.01077952
   0.01373303 -0.0020059   0.00710426  0.01096855]
 [-0.03359409 -0.03590824 -0.04219388 -0.02039877 -0.04753714  0.0036312
  -0.01310426  0.04110752 -0.03078072  0.03298495]
 [ 0.01544186  0.02101154 -0.00152663  0.03602524 -0.00822828  0.01963588
   0.03689197 -0.02751786  0.00354798 -0.0210005 ]]
